AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchgateway:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: sample.lambda_handler
      Runtime: python3.9
      CodeUri: s3://lambdaoutputbucket-556174328764/searchfunction/searchfunction.zip
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::556174328764:role/CodePipelineLambdaExecRole'
